export default{
    path:'/',
    component:()=>import ('../layout/Index'),
    children:[
      //首页
      {
        path:'',
        name:'home',
        component:()=>import('../views/home/Home'),
        meta:{  //路由的数据
          title:'首页',
          img:'/image/shouye.svg'
        }
      },
      //课程管理
      {
        path:'course',
        name:'course',
        component:{  //直接提供组件的render,不需要vue文件了
          render:h => <router-view/>
        },
        redirect:'/course/course-list',
        meta:{ 
          title:'课程管理',
          img:'/image/kecheng.png'
        },
        children:[
          //课程列表
          {
            path:'course-list',
            name:'course-list',
            component:()=>import('../views/course/CourseList'),
            meta:{ 
              title:'课程列表',
            }
          },
          //课程消耗
          {
            path:'course-consumption',
            name:'course-consumption',
            component:()=>import('../views/course/CourseConsumption'),
            meta:{ 
              title:'课程消耗',
            }
          },
        ]
      },
      //班级管理
      {
        path:'class',
        name:'class',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/class/manage',
        meta:{ 
          title:'班级管理',
          img:'/image/banji.png'
        },
        children:[
          //班级管理
          {
            path:'manage',
            name:'manage',
            component:()=>import('../views/class/Manage'),
            meta:{ 
              title:'班级管理',
            }
          },
          //课时管理
          {
            path:'class-hour',
            name:'class-hour',
            component:()=>import('../views/class/ClassHour'),
            meta:{ 
              title:'课时管理',
            }
          },
          //教室管理
          {
            path:'class-room',
            name:'class-room',
            component:()=>import('../views/class/ClassRoom'),
            meta:{ 
              title:'教室管理',
            }
          },
          //课程表
          {
            path:'class-schedulCard',
            name:'class-schedulCard',
            component:()=>import('../views/class/ClassSchedulCard'),
            meta:{ 
              title:'课程表',
            }
          },
        ]
      },
      //订单管理
      {
        path:'order',
        name:'order',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/order/order-list',
        meta:{ 
          title:'订单管理',
          img:'/image/dingdan.svg'
        },
        children:[
          //订单列表
          {
            path:'order-list',
            name:'order-list',
            component:()=>import('../views/order/OrderList'),
            meta:{ 
              title:'订单列表',
            }
          },
          //退款管理
          {
            path:'refund',
            name:'refund',
            component:()=>import('../views/order/Refund'),
            meta:{ 
              title:'退款管理',
            }
          },
        ]
      },
      //学员管理
      {
        path:'student',
        name:'student',
        component:()=>import('../views/student/Student'),
        meta:{ 
          title:'学员管理',
          img:'/image/xueyuan.png'
        },
      },
      //教师管理
      {
        path:'teacher',
        name:'teacher',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/teacher/campus',
        meta:{ 
          title:'教师管理',
          img:'/image/jiaoshi.png'
        },
        children:[
          //校区管理
          {
            path:'campus',
            name:'campus',
            component:()=>import('../views/teacher/Campus'),
            meta:{ 
              title:'校区管理',
            }
          },
          //教师管理
          {
            path:'teacher-manage',
            name:'teacher-manage',
            component:()=>import('../views/teacher/Teacher'),
            meta:{ 
              title:'教师管理',
            }
          },
        ]
      },
      //文章管理
      {
        path:'article',
        name:'article',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/article/banner',
        meta:{ 
          title:'文章管理',
          img:'/image/wenzhang.png'
        },
        children:[
          //轮播图管理
          {
            path:'banner',
            name:'banner',
            component:()=>import('../views/article/Banner'),
            meta:{ 
              title:'轮播图管理',
            }
          },
          //资讯管理
          {
            path:'news',
            name:'news',
            component:()=>import('../views/article/News'),
            meta:{ 
              title:'资讯管理',
            }
          },
          //活动管理
          {
            path:'activity',
            name:'activity',
            component:()=>import('../views/article/Activity'),
            meta:{ 
              title:'活动管理',
            }
          },
          //公开课管理
          {
            path:'public',
            name:'public',
            component:()=>import('../views/article/Public'),
            meta:{ 
              title:'公开课管理',
            }
          },
        ] 
      },
      //促销活动
      {
        path:'sales',
        name:'sales',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/sales/kill',
        meta:{ 
          title:'促销活动',
          img:'/image/cuxiao.svg'
        },
        children:[
          //秒杀活动
          {
            path:'kill',
            name:'kill',
            component:()=>import('../views/sales/SecondKill'),
            meta:{ 
              title:'秒杀活动',
            }
          },
          //优惠券管理
          {
            path:'coupon',
            name:'coupon',
            component:()=>import('../views/sales/Coupon'),
            meta:{ 
              title:'优惠券管理',
            }
          },
        ]
      },
      //统计分析
      {
        path:'statistics',
        name:'statistics',
        component:()=>import('../views/statistics/Statistics'),
        meta:{ 
          title:'统计分析',
          img:'/image/tongji.png'
        },
      },
      //系统设置
      {
        path:'setting',
        name:'setting',
        component:{  
          render:h => <router-view/>
        },
        redirect:'/setting/staff',
        meta:{ 
          title:'系统设置',
          img:'/image/shezhi.svg'
        },
        children:[
          //员工管理
          {
            path:'staff',
            name:'staff',
            component:()=>import('../views/setting/Staff'),
            meta:{ 
              title:'员工管理',
            }
          },
          //角色管理
          {
            path:'role',
            name:'role',
            component:()=>import('../views/setting/Role'),
            meta:{ 
              title:'角色管理',
            }
          },
          //关于我们
          {
            path:'about',
            name:'about',
            component:()=>import('../views/setting/About'),
            meta:{ 
              title:'关于我们',
            }
          },
          //通用设置
          {
            path:'currency',
            name:'currency',
            component:()=>import('../views/setting/Currency'),
            meta:{ 
              title:'通用设置',
            }
          },
          //消息
          {
            path:'message',
            name:'message',
            component:()=>import('../views/setting/Message'),
            meta:{ 
              title:'消息',
            }
          },
          //操作日志
          {
            path:'operation',
            name:'operation',
            component:()=>import('../views/setting/Operation'),
            meta:{ 
              title:'操作日志',
            }
          },
        ]
        
      },
    ]
  }